# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse robots.txt
#'
#' @noRd
#'
rep_parse <- function(content) {
    .Call(`_rep_rep_parse`, content)
}

#' Path allowed
#'
#' @noRd
#'
rep_path_allowed <- function(xp, path, agent = "*") {
    .Call(`_rep_rep_path_allowed`, xp, path, agent)
}

